Blog/Areas/Admin/Controllers/CommentController.cs
using Blog.Infrastructura;
using DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Areas.Admin.Controllers
{
    /// <summary>
    /// Управление комментариями
    /// </summary>
    public class CommentController : BaseController
    {
        /// <summary>
        /// Страница с управлением комментариев
        /// </summary>
        /// <returns></returns>
        [FilterUser(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Обновление Ajax запросом таблицы комментариев
        /// </summary>
        /// <returns></returns>
        public ActionResult AjaxComment(string user)
        {
            var comment = AdminServices.Comments.GetComments(user);
            return View(comment);
        }
        /// <summary>
        /// Удаление коментария
        /// </summary>
        /// <param name="id">Ид комментария</param>
        /// <param name="PareantId">Ид родительского комментария</param>
        /// <returns></returns>
        public ActionResult DeleteComment(int id,int? PareantId)
        {
            AdminServices.Comments.DeleteComment(id,PareantId);
            return Json("Комментарий удален");
        }
        /// <summary>
        /// Редактирование комментария
        /// </summary>
        /// <param name="id">Ид комментария</param>
        /// <param name="content">Содержимое комментария</param>
        /// <returns></returns>
        public ActionResult EditComment(int id,string content)
        {
            AdminServices.Comments.EditComment(id, content);
            return Json("Комментарий успешно отредактирован");
        }
        public ActionResult AutocompleteSearch(string term)
        {
                var model = AdminServices.Comments.Search(term);
                var models = model.Select(x => new { value = x.UserName }).Distinct().ToList();
                return Json(models, JsonRequestBehavior.AllowGet);
            
        }
    }
}

Blog/Areas/Admin/Controllers/PostsController.cs
using Blog.Infrastructura;
using IServices.Models.Post;
using IServices.Models.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/// <summary>
/// Контролеры Админки
/// </summary>
namespace Blog.Areas.Admin.Controllers
{
    /// <summary>
    /// Контролер отвечающий за управленние постами
    /// </summary>
    /// <seealso cref="Blog.Areas.Admin.Controllers.BaseController" />
    public class PostsController : BaseController
    {
        #region Управления постами
        /// <summary>
        /// Страница с добавлением нового поста
        /// </summary>
        /// <returns></returns>
        public ActionResult NewPost()
        {
            return View();
        }
        /// <summary>
        /// Добавление поста
        /// </summary>
        /// <param name="model">Модель поста</param>
        /// <param name="IdCategory">Ид категории</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult NewPost(ModelNewPost model, int IdCategory, HttpPostedFileBase Upload, int User)
        {
            string map = Server.MapPath("~/img/");
            AdminServices.ControlPosts.Image(Upload, map, model);
            AdminServices.ControlPosts.AddPost(model, IdCategory,User);
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Создает перемнную в которой находится путь для сохранения файла и далее выполняет метод сохраняющий изображения 
        /// </summary>
        /// <param name="Upload">Файл</param>
        /// <param name="CKEditorFuncNum">Идентификационный номер анонимного функции обратного вызова после загрузки</param>
        /// <returns></returns>
        public ActionResult AddImage(HttpPostedFileBase Upload, string CKEditorFuncNum, ModelNewPost model)
        {
            string map = Server.MapPath("~/img/");
            string output = AdminServices.ControlPosts.ProcessRequest(Upload, CKEditorFuncNum, map, model);
            return Content(output);
        }
        /// <summary>
        /// Страница с управлением постами
        /// </summary>
        /// <returns></returns>
        [FilterUser(Roles = "Admin")]
        public ActionResult Index()
        {

            return View();
        }
        /// <summary>
        /// Удаление постов
        /// </summary>
        /// <param name="id">Список выбраных постов</param>
        /// <returns></returns>
        public ActionResult DeletePosts(int id)
        {
            string map = Server.MapPath("~/img/");
         
            AdminServices.ControlPosts.DeletePosts(id, map);
            return Json("Пост успешно удален");
        }
        /// <summary>
        /// Редактирование поста.
        /// </summary>
        /// <param name="id">ИД поста.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult EditPost(int id)
        {
            var model = AdminServices.ControlPosts.GetEditPost(id);
            return View(model);
        }
        /// <summary>
        /// Редактирование поста
        /// </summary>
        /// <param name="model">Модель поста</param>
        /// <param name="IdCategory">ID категории</param>
        /// <param name="Upload">Изображение для Preview</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditPost(ModelNewPost model, int IdCategory, HttpPostedFileBase Upload)
        {
            string map = Server.MapPath("~/img/");
            AdminServices.ControlPosts.Image(Upload, map, model);
            AdminServices.ControlPosts.EditPost(model, IdCategory);
            return RedirectToAction("Index");

        }
        /// <summary>
        /// Ajaxes обновление страницы.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult AjaxPosts()
        {
            var posts = AdminServices.ControlPosts.PostPreview();
            return View(posts);
        }
        public ActionResult AutocompleteSearch(string term)
        {
            var model = AdminServices.Comments.Search(term);
            var models = model.Select(x => new { value = x.UserName }).Distinct().ToList();
            return Json(models, JsonRequestBehavior.AllowGet);

        }
        #endregion
    }
}

Blog/Areas/Admin/Controllers/UsersController.cs
using Blog.Infrastructura;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/// <summary>
/// Контролеры админки.
/// </summary>
namespace Blog.Areas.Admin.Controllers
{
    /// <summary>
    /// Контролер отвечающий за управлениями пользователями
    /// </summary>
    /// <seealso cref="Blog.Areas.Admin.Controllers.BaseController" />
    public class UsersController : BaseController
    {

        #region Страница с пользователями
        /// <summary>
        /// Страница с таблицей всех пользователй
        /// </summary>
        /// <returns></returns>
        [FilterUser(Roles = "Admin")]
        public ActionResult Index()
        {

            var usres = AdminServices.Users.Users();
            return View(usres);
        }
        /// <summary>
        /// Удаляет выбраных пользователей с БД 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteUsers()
        {
            var list = Request.Form["list"].Split(',').Select(Int32.Parse).ToList();
            AdminServices.Users.Delete(list);
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Изменяет статус пользователя в БД на "Заблокированный"
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult BlockUsers()
        {
            var list = Request.Form["list"].Split(',').Select(Int32.Parse).ToList();
            AdminServices.Users.Block(list);
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Вывод содержимое таблицы пользователей  
        /// </summary>
        /// <returns></returns>
        public ActionResult AjaxUsers()
        {
            var users = AdminServices.Users.Users();
            return View(users);
        }
        /// <summary>
        /// Регистрирует нового пользователя и отправляет ему писмо на почту с потверждением аккаунта
        /// </summary>
        /// <param name="userName">Логин пользователя</param>
        /// <param name="email">Почта пользователя</param>
        /// <param name="password">Пароль пользователя</param>
        /// <param name="dataBirth">Дата Рождения пользователя</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult AddUser(string userName, string email, string password, DateTime dataBirth)
        {

            var salt = AdminServices.Users.Register(userName, password, dataBirth, email);
            WebUser.SendMail("Подтвердите регистрацию", email,
                $@"Для завершения регистрации перейдите по 
                 <a href='{Url.Action("Confrimed", "Account", new { area = "", salt = salt, userName = userName }, Request.Url.Scheme)}'
                 title='Подтвердить регистрацию'>ссылке</a>");
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Назначение роли пользователю
        /// </summary>
        /// <param name="role">Выбранная роль</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult roleUsers(string role)
        {
            var list = Request.Form["list"].Split(',').Select(Int32.Parse).ToList();
            AdminServices.Users.roleUsers(list, role);
            return Json("Запрос успешно выполнен");
        }
        #endregion
    }
}

Blog/Areas/Admin/Views/Comment/AjaxComment.cshtml
@model IEnumerable<IServices.Models.Post.ModelComment>
@{    
    Layout=null;
}

<div class="col-md-10">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="portlet box purple">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-cogs"></i>Управление комментариями
            </div>
            <div class="actions">
           
                
            </div>
        </div>
        <div class="portlet-body">
            <div id="the-basics" class="col-md-4">
               
            </div>
            <div class="form-group">
                <table class="table table-striped table-bordered table-hover" id="sample_3">
                    <thead>
                        <tr>
                            <th class="table-checkbox">

                            </th>
                            <th>
                                Содержимое комментария
                            </th>
                            <th>
                                Пост
                            </th>
                            <th>
                                Дата создания комментария
                            </th>
                            <th>
                                Пользователь
                            </th>
                            <th class="table-checkbox">

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var comment in Model)
                        {
                            <tr class="odd gradeX">
                                <td>
                                    <a data-toggle="modal" data-target="#EditComment" style="text-decoration: none; " class="editComment" alt="@comment.Id" name="@comment.ContentComment" title="Редактировать содержимое">
                                        <span class="glyphicon glyphicon-cog">

                                        </span>
                                    </a>
                                </td>

                                <td>
                                    <a data-toggle="modal" data-target="#EditComment" style="text-decoration: none; " class="editComment" alt="@comment.Id" name="@comment.ContentComment" title="Редактировать содержимое">
                                        @comment.ContentComment
                                    </a>


                                </td>

                                <td>
                                    <a href="@Url.Action("Index","Posts")">@comment.Post[0].NamePost</a>
                                </td>
                                <td>
                                    @comment.DateAddPost.ToLongDateString()
                                </td>
                                <td>
                                    <a href="@Url.Action("Index","Users")">@comment.User[0].UserName</a>
                                </td>

                                <td>
                                    <a data-toggle="modal" data-target="#deleteCommentModal" style="text-decoration: none; " class="deleteComment" alt="@comment.Id" title="@comment.PareantId">
                                        <span class="glyphicon glyphicon-trash">

                                        </span>
                                    </a>

                                </td>
                            </tr>
                        }

                    </tbody>

                </table>
                <div >
                    <label for="Search">Поиск по пользователю</label>
                </div>
                <div class="col-md-2">
                 
                    <input type="text" name="Search" id="inputSearch" class="form-control" data-autocomplete-source='@Url.Action("AutocompleteSearch", "Comment")'   />
          
                </div>
                <input type="submit" class="btn btn-default" value="Поиск" id="search"/>
            </div>
        </div>



    </div>
    <!-- END EXAMPLE TABLE PORTLET-->
</div>

<script>
    $(function () {
        $("[data-autocomplete-source]").each(function () {
            var target = $(this);
            target.autocomplete({ source: target.attr("data-autocomplete-source") });
        });
    });
</script>

<!-- Начало модальных окн-->

<!--Удаление комментария-->
<div id="deleteCommentModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Вы действительно хотите удалить данный комментарий?</h4>
            </div>
            <div class="modal-body">
                <div class="form-group" align="center">
                    <button class="btn btn-danger" data-dismiss="modal" id="deleteCommentYes">Да</button>
                    <button class="btn btn-default" type="button" data-dismiss="modal">Нет</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Конец удаление комментария-->

<!--Редактирование комментария-->
<div id="EditComment" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Редактирование коментария</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                   
                    <div class="col-md-10" align="center">
                        <textarea maxlength="150" rows="4"  id="editCommentArea" class="form-control" style="margin-bottom:25px;"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-success" data-dismiss="modal" id="EditCommentSave">Сохранить</button>
                    <button class="btn btn-default" type="button" data-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!--Конец редактирование комментария-->

<!--Конец модальных окн-->
<script>

    $(document).ready(function () {
        var deleteComment;
        var PareantId;
        var editCommentId;
        var editContentComment;
        $('#search').click(function () {
            var inputSearch = $('#inputSearch').val();
            var url = '@Url.Action("AjaxComment", "Comment")?user=' + inputSearch;
            $('#PanelComments').load(url);
        });
            $('.deleteComment').click(function () {
                deleteComment = $(this).attr('alt');
                PareantId = $(this).attr('title');
            })
            $('#deleteCommentYes').click(function () {

                var data = new FormData();
                data.append("id", deleteComment);
                data.append("PareantId", PareantId);
                $.ajax({
                    url: 'Comment/DeleteComment',
                    type: 'post',
                    contentType: false,
                    processData: false,
                    data: data,
                    beforeSend: function () { console.log(deleteComment); },
                    success: function (data) {
                        upPosts();
                        console.log(data);
                    }
                });
            });
            $('.editComment').click(function () {
                editCommentId = $(this).attr('alt');
                editContentComment = $(this).attr('name');
                document.getElementById('editCommentArea').value = editContentComment;
            })
            $('#EditCommentSave').click(function () {
                var content = $('#editCommentArea').val();
                var data = new FormData();
                data.append("id", editCommentId);
                data.append("content", content);
                $.ajax({
                    url: 'Comment/EditComment',
                    type: 'post',
                    contentType: false,
                    processData: false,
                    data: data,
                    beforeSend: function () { console.log(editCommentId); },
                    success: function (data) {
                        upPosts();
                        console.log(data);
                    }
                });

            });
            function upPosts() {

                $('#PanelComments').load("@Url.Action("AjaxComment", "Comment")");
            };
        });
    });
</script>

Blog/Areas/Admin/Views/Comment/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="PanelComments"></div>

@section scripts{
    <script>
      
            $(document).ready(function () {
                $('#PanelComments').load("@Url.Action("AjaxComment", "Comment")");


            });


    </script>
}