Blog/Areas/Admin/Controllers/DashboardController.cs
using Blog.Infrastructura;
using IServices.Models.Post;
using Services.Exextension;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/// <summary>
/// Контролеры админки.
/// </summary>
namespace Blog.Areas.Admin.Controllers
{
    /// <summary>
    /// Контролер главной части админки.
    /// </summary>
    /// <seealso cref="Blog.Areas.Admin.Controllers.BaseController" />
    public class DashboardController : BaseController
    {
        // GET: Admin/Home
        /// <summary>
        /// Главная страница админки
        /// </summary>
        /// <returns></returns>
        [FilterUser(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Информация о количестве просмотров
        /// </summary>
        /// <returns></returns>
        public ActionResult Viwes()
        {
            int count = AdminServices.ControlPosts.CountViews();
            return View(count);
        }
        /// <summary>
        /// Информация о количестве лайков
        /// </summary>
        /// <returns></returns>
        public ActionResult Likes()
        {
            int count = AdminServices.ControlPosts.CountLike();
            return View(count);
        }
        /// <summary>
        /// Информация о количестве постов
        /// </summary>
        /// <returns></returns>
        public ActionResult CountPosts()
        {
            int count = AdminServices.ControlPosts.CountPosts();
            return View(count);
        }
        /// <summary>
        /// Информация о количестве пользователей
        /// </summary>
        /// <returns></returns>
        public ActionResult CountsUsers()
        {
            int count = AdminServices.ControlPosts.CountUsers();
            return View(count);
        }
        /// <summary>
        /// Информация о количестве комментарий
        /// </summary>
        /// <returns></returns>
        public ActionResult CountsComments()
        {
            int count = AdminServices.ControlPosts.CountComments();
            return View(count);
        }
    }


}

Blog/Areas/Admin/Controllers/PostsController.cs
using Blog.Infrastructura;
using IServices.Models.Post;
using IServices.Models.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/// <summary>
/// Контролеры Админки
/// </summary>
namespace Blog.Areas.Admin.Controllers
{
    /// <summary>
    /// Контролер отвечающий за управленние постами
    /// </summary>
    /// <seealso cref="Blog.Areas.Admin.Controllers.BaseController" />
    public class PostsController : BaseController
    {
        #region Управления постами
        /// <summary>
        /// Страница с добавлением нового поста
        /// </summary>
        /// <returns></returns>
        public ActionResult NewPost()
        {
            return View();
        }
        /// <summary>
        /// Добавление поста
        /// </summary>
        /// <param name="model">Модель поста</param>
        /// <param name="IdCategory">Ид категории</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult NewPost(ModelNewPost model, int IdCategory, HttpPostedFileBase Upload, int User)
        {
            string map = Server.MapPath("~/img/");
            AdminServices.ControlPosts.Image(Upload, map, model);
            AdminServices.ControlPosts.AddPost(model, IdCategory,User);
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Создает перемнную в которой находится путь для сохранения файла и далее выполняет метод сохраняющий изображения 
        /// </summary>
        /// <param name="Upload">Файл</param>
        /// <param name="CKEditorFuncNum">Идентификационный номер анонимного функции обратного вызова после загрузки</param>
        /// <returns></returns>
        public ActionResult AddImage(HttpPostedFileBase Upload, string CKEditorFuncNum, ModelNewPost model)
        {
            string map = Server.MapPath("~/img/");
            string output = AdminServices.ControlPosts.ProcessRequest(Upload, CKEditorFuncNum, map, model);
            return Content(output);
        }
        /// <summary>
        /// Страница с управлением постами
        /// </summary>
        /// <returns></returns>
        [FilterUser(Roles = "Admin")]
        public ActionResult Index()
        {

            return View();
        }
        /// <summary>
        /// Удаление постов
        /// </summary>
        /// <param name="id">Список выбраных постов</param>
        /// <returns></returns>
        public ActionResult DeletePosts(int id)
        {
            string map = Server.MapPath("~/img/");
         
            AdminServices.ControlPosts.DeletePosts(id, map);
            return Json("Пост успешно удален");
        }
        /// <summary>
        /// Редактирование поста.
        /// </summary>
        /// <param name="id">ИД поста.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult EditPost(int id)
        {
            var model = AdminServices.ControlPosts.GetEditPost(id);
            return View(model);
        }
        /// <summary>
        /// Редактирование поста
        /// </summary>
        /// <param name="model">Модель поста</param>
        /// <param name="IdCategory">ID категории</param>
        /// <param name="Upload">Изображение для Preview</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditPost(ModelNewPost model, int IdCategory, HttpPostedFileBase Upload)
        {
            string map = Server.MapPath("~/img/");
            AdminServices.ControlPosts.Image(Upload, map, model);
            AdminServices.ControlPosts.EditPost(model, IdCategory);
            return RedirectToAction("Index");

        }
        /// <summary>
        /// Ajaxes обновление страницы.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult AjaxPosts()
        {
            var posts = AdminServices.ControlPosts.PostPreview();
            return View(posts);
        }
        public ActionResult AutocompleteSearch(string term)
        {
            var model = AdminServices.Comments.Search(term);
            var models = model.Select(x => new { value = x.UserName }).Distinct().ToList();
            return Json(models, JsonRequestBehavior.AllowGet);

        }
        #endregion
    }
}

Blog/Areas/Admin/Controllers/UsersController.cs
using Blog.Infrastructura;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/// <summary>
/// Контролеры админки.
/// </summary>
namespace Blog.Areas.Admin.Controllers
{
    /// <summary>
    /// Контролер отвечающий за управлениями пользователями
    /// </summary>
    /// <seealso cref="Blog.Areas.Admin.Controllers.BaseController" />
    public class UsersController : BaseController
    {

        #region Страница с пользователями
        /// <summary>
        /// Страница с таблицей всех пользователй
        /// </summary>
        /// <returns></returns>
        [FilterUser(Roles = "Admin")]
        public ActionResult Index()
        {

            var usres = AdminServices.Users.Users();
            return View(usres);
        }
        /// <summary>
        /// Удаляет выбраных пользователей с БД 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteUsers()
        {
            var list = Request.Form["list"].Split(',').Select(Int32.Parse).ToList();
            AdminServices.Users.Delete(list);
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Изменяет статус пользователя в БД на "Заблокированный"
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult BlockUsers()
        {
            var list = Request.Form["list"].Split(',').Select(Int32.Parse).ToList();
            AdminServices.Users.Block(list);
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Вывод содержимое таблицы пользователей  
        /// </summary>
        /// <returns></returns>
        public ActionResult AjaxUsers()
        {
            var users = AdminServices.Users.Users();
            return View(users);
        }
        /// <summary>
        /// Регистрирует нового пользователя и отправляет ему писмо на почту с потверждением аккаунта
        /// </summary>
        /// <param name="userName">Логин пользователя</param>
        /// <param name="email">Почта пользователя</param>
        /// <param name="password">Пароль пользователя</param>
        /// <param name="dataBirth">Дата Рождения пользователя</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult AddUser(string userName, string email, string password, DateTime dataBirth)
        {

            var salt = AdminServices.Users.Register(userName, password, dataBirth, email);
            WebUser.SendMail("Подтвердите регистрацию", email,
                $@"Для завершения регистрации перейдите по 
                 <a href='{Url.Action("Confrimed", "Account", new { area = "", salt = salt, userName = userName }, Request.Url.Scheme)}'
                 title='Подтвердить регистрацию'>ссылке</a>");
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Назначение роли пользователю
        /// </summary>
        /// <param name="role">Выбранная роль</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult roleUsers(string role)
        {
            var list = Request.Form["list"].Split(',').Select(Int32.Parse).ToList();
            AdminServices.Users.roleUsers(list, role);
            return Json("Запрос успешно выполнен");
        }
        #endregion
    }
}

Blog/Areas/Admin/Views/Dashboard/CountPosts.cshtml
@model int
@{
    Layout = null;
}
<a href="@Url.Action("Index","Posts")">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat2">
            <div class="display">
                <div class="number">
                    <h3 class="font-blue-sharp">@Model</h3>
                    <small>Постов</small>
                </div>
                <div class="icon">
                    <i class="icon-docs"></i>
                </div>
            </div>
        </div>
    </div>
</a>

Blog/Areas/Admin/Views/Dashboard/CountsComments.cshtml
@model int
@{
    Layout = null;
}

<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
    <div class="dashboard-stat2">
        <div class="display">
            <div class="number">
                <h3 class="font-red-haze">@Model</h3>
                <small>Комментарий</small>
            </div>
            <div class="icon">
                <i class="icon-note"></i>
            </div>
        </div>
    </div>
</div>

Blog/Areas/Admin/Views/Dashboard/CountsUsers.cshtml
@model int
@{
    Layout = null;
}
<a href="@Url.Action("Index","Users")">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <div class="dashboard-stat2">
            <div class="display">
                <div class="number">
                    <h3 class="font-purple-soft">@Model</h3>
                    <small>Пользователей</small>
                </div>
                <div class="icon">
                    <i class="icon-user"></i>
                </div>
            </div>

        </div>
    </div>
</a>

Blog/Areas/Admin/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<!-- Начало статистики сайта -->
@Html.Action("CountsUsers", "Dashboard")
@Html.Action("CountPosts", "Dashboard")
@Html.Action("Likes", "Dashboard")
@Html.Action("Viwes", "Dashboard")
@Html.Action("CountsComments", "Dashboard")
<!-- Конец статистики сайта -->

Blog/Areas/Admin/Views/Dashboard/Likes.cshtml
@model int
@{
    Layout = null;
}

<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
    <div class="dashboard-stat2">
        <div class="display">
            <div class="number">
                <h3 class="font-red-haze">@Model</h3>
                <small>Лайков</small>
            </div>
            <div class="icon">
                <i class="icon-like"></i>
            </div>
        </div>

    </div>
</div>

Blog/Areas/Admin/Views/Dashboard/Viwes.cshtml
@model int
@{
    Layout=null;
}

<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
    <div class="dashboard-stat2">
        <div class="display">
            <div class="number">
                <h3 class="font-blue-sharp">@Model</h3>
                <small>Просмотров</small>
            </div>
            <div class="icon">
                <i class="icon-screen-desktop"></i>
            </div>
        </div>

    </div>
</div>