Blog/Areas/Admin/Controllers/CategoriesController.cs
using Blog.Infrastructura;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/// <summary>
/// Контролеры админки.
/// </summary>
namespace Blog.Areas.Admin.Controllers
{
    /// <summary>
    /// Контролер отвечающий за управлением категории.
    /// </summary>
    /// <seealso cref="Blog.Areas.Admin.Controllers.BaseController" />
    public class CategoriesController : BaseController
    {

        #region Страница с категориями
        /// <summary>
        /// Страница с категориями 
        /// </summary>
        /// <returns></returns>
        [FilterUser(Roles = "Admin")]
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Добавление родительской категории
        /// </summary>
        /// <param name="name">Название категории</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddMainCategory(string name)
        {
            AdminServices.Categories.AddCategory(name);
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Добавление дочерний категории
        /// </summary>
        /// <param name="namePareantCategory">Имя родительской категории</param>
        /// <param name="nameChild">Название новой дочерний категории</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddChildCategory(string namePareantCategory, string nameChild)
        {
            AdminServices.Categories.addChildCategory(namePareantCategory, nameChild);
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Удаление родительской категории
        /// </summary>
        /// <param name="name">Имя родительской категории</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeletePareant(string name)
        {
            AdminServices.Categories.DeletePareant(name);
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Удаляет дочернию категорию
        /// </summary>
        /// <param name="NamePareant">Имя родительской категории</param>
        /// <param name="NameChild">Имя дочерний категории</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteChild(string NamePareant, string NameChild)
        {
            AdminServices.Categories.DeleteChild(NamePareant, NameChild);
            return Json("Запрос успешно выполнен");
        }
        /// <summary>
        /// Изменяет название выбранной категории
        /// </summary>
        /// <param name="namePareant">Выбраная родительская категория</param>
        /// <param name="newName">Новое название категории</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ChangeNamePareant(string namePareant, string newName)
        {
            AdminServices.Categories.ChangeNamePareant(namePareant, newName);
            return Json("Запрос успешно выполнен");
        }
        [HttpPost]
        public ActionResult ChangeNameChild(string namePareant, string childName, string newName)
        {
            AdminServices.Categories.ChangeNameChild(namePareant, childName, newName);
            return Json("Запрос успешно выполнен");
        }

        /// <summary>
        /// Ajax обновление категорий.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult AjaxCategories()
        {

            return View();
        }
        /// <summary>
        /// Вывод категорий.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult SelectCategory()
        {
            var model = AdminServices.ControlPosts.GetCategory();
            return View(model);
        }
       
        #endregion
    }
}

Blog/Areas/Admin/Controllers/PostsController.cs
using Blog.Infrastructura;
using IServices.Models.Post;
using IServices.Models.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

/// <summary>
/// Контролеры Админки
/// </summary>
namespace Blog.Areas.Admin.Controllers
{
    /// <summary>
    /// Контролер отвечающий за управленние постами
    /// </summary>
    /// <seealso cref="Blog.Areas.Admin.Controllers.BaseController" />
    public class PostsController : BaseController
    {
        #region Управления постами
        /// <summary>
        /// Страница с добавлением нового поста
        /// </summary>
        /// <returns></returns>
        public ActionResult NewPost()
        {
            return View();
        }
        /// <summary>
        /// Добавление поста
        /// </summary>
        /// <param name="model">Модель поста</param>
        /// <param name="IdCategory">Ид категории</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult NewPost(ModelNewPost model, int IdCategory, HttpPostedFileBase Upload, int User)
        {
            string map = Server.MapPath("~/img/");
            AdminServices.ControlPosts.Image(Upload, map, model);
            AdminServices.ControlPosts.AddPost(model, IdCategory,User);
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Создает перемнную в которой находится путь для сохранения файла и далее выполняет метод сохраняющий изображения 
        /// </summary>
        /// <param name="Upload">Файл</param>
        /// <param name="CKEditorFuncNum">Идентификационный номер анонимного функции обратного вызова после загрузки</param>
        /// <returns></returns>
        public ActionResult AddImage(HttpPostedFileBase Upload, string CKEditorFuncNum, ModelNewPost model)
        {
            string map = Server.MapPath("~/img/");
            string output = AdminServices.ControlPosts.ProcessRequest(Upload, CKEditorFuncNum, map, model);
            return Content(output);
        }
        /// <summary>
        /// Страница с управлением постами
        /// </summary>
        /// <returns></returns>
        [FilterUser(Roles = "Admin")]
        public ActionResult Index()
        {

            return View();
        }
        /// <summary>
        /// Удаление постов
        /// </summary>
        /// <param name="id">Список выбраных постов</param>
        /// <returns></returns>
        public ActionResult DeletePosts(int id)
        {
            string map = Server.MapPath("~/img/");
         
            AdminServices.ControlPosts.DeletePosts(id, map);
            return Json("Пост успешно удален");
        }
        /// <summary>
        /// Редактирование поста.
        /// </summary>
        /// <param name="id">ИД поста.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult EditPost(int id)
        {
            var model = AdminServices.ControlPosts.GetEditPost(id);
            return View(model);
        }
        /// <summary>
        /// Редактирование поста
        /// </summary>
        /// <param name="model">Модель поста</param>
        /// <param name="IdCategory">ID категории</param>
        /// <param name="Upload">Изображение для Preview</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditPost(ModelNewPost model, int IdCategory, HttpPostedFileBase Upload)
        {
            string map = Server.MapPath("~/img/");
            AdminServices.ControlPosts.Image(Upload, map, model);
            AdminServices.ControlPosts.EditPost(model, IdCategory);
            return RedirectToAction("Index");

        }
        /// <summary>
        /// Ajaxes обновление страницы.
        /// </summary>
        /// <returns>ActionResult.</returns>
        public ActionResult AjaxPosts()
        {
            var posts = AdminServices.ControlPosts.PostPreview();
            return View(posts);
        }
        public ActionResult AutocompleteSearch(string term)
        {
            var model = AdminServices.Comments.Search(term);
            var models = model.Select(x => new { value = x.UserName }).Distinct().ToList();
            return Json(models, JsonRequestBehavior.AllowGet);

        }
        #endregion
    }
}

Blog/Areas/Admin/Views/Posts/AjaxPosts.cshtml
@model IEnumerable<IServices.Models.Post.ModelPostPreview>
@{
    Layout = null;
}
<div class="col-md-10">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="portlet box purple">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-cogs"></i>Управление постами
             
            </div>
       
            <div class="actions">

                <a href="@Url.Action("NewPost","Posts")" class="btn btn-default btn-sm" title="Добавить пост">
                    <i class="fa fa-plus"></i> Добавить пост
                </a>
             

            </div>
        </div>
        <div class="portlet-body">
            <table class="table table-striped table-bordered table-hover" id="sample_3">
                <thead>
                    <tr>
                        <th class="table-checkbox">

                        </th>
                        <th>
                            Название поста
                        </th>
                        <th>
                            Категория поста
                        </th>
                        <th>
                            Дата создания поста
                        </th>
                        <th class="table-checkbox">

                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var post in Model)
                    {
                        <tr class="odd gradeX">
                            <td>
                                <span><a href="@Url.Action("EditPost","Posts", new { id = post.PostID })"><i class="fa fa-cogs" title="Редактировать пост"></i> </a></span>
                            </td>

                            <td>
                                <a href="@Url.Action("EditPost","Posts", new { id = post.PostID })" title="Редактировать пост" id="deletePost">
                                    @post.NamePost
                                </a>
                            </td>

                            <td>
                                @post.Category.Name

                            </td>
                            <td>
                                @post.dateAddPost.ToLongDateString()
                            </td>
                            <td>
                                <a data-toggle="modal" data-target="#deltePostModal" style="text-decoration: none; " class="deletePost" alt="@post.PostID">
                                    <span class="glyphicon glyphicon-trash">

                                    </span>
                                </a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
       
     

    </div>
    <!-- END EXAMPLE TABLE PORTLET-->
</div>
 <!-- Начало модальных окн-->
<div id="deltePostModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" type="button" data-dismiss="modal">×</button>
                <h4 class="modal-title">Вы действительно хотите удалить данный пост?</h4>
            </div>
            <div class="modal-body">
                <div class="form-group" align="center">
                    <button class="btn btn-danger" data-dismiss="modal" id="deletePostYes" >Да</button>
                    <button class="btn btn-default" type="button" data-dismiss="modal">Нет</button>
                </div>  
            </div>
        </div>
    </div>
</div>
<!--Конец модальных окн-->
<script>
    $(document).ready(function () {
        var deletePost;
        $('.deletePost').click(function () {
            deletePost = $(this).attr('alt');
        })
        $('#deletePostYes').click(function () {
                
                var data = new FormData();
                data.append("id", deletePost);
                $.ajax({
                    url: 'Posts/DeletePosts',
                    type: 'post',
                    contentType: false,
                    processData: false,
                    data: data,
                    beforeSend: function () { console.log(deletePost); },
                    success: function (data) {
                        upPosts();
                        console.log(data);
                    }
                });
        
            });
            function upPosts() {

                $('#PanelPosts').load("@Url.Action("AjaxPosts", "Posts")");
            };
        });
</script>

Blog/Areas/Admin/Views/Posts/EditPost.cshtml
@model IServices.Models.Post.ModelPost
@{
    ViewBag.Title = "EditPost";
}

<div class="col-md-12">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-cogs">&nbsp;</i>Добавить пост
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
                <a href="javascript:;" id="reloadUsers" class="reload" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">

            <div class="form-group">
                <input type="hidden" id="id" name="id" value="@Model.PostID" />
                <label for="NamePost" class="col-sm-2 control-label">Название</label>
                <div class="col-md-10">
                    <input type="text" class="form-control" id="NamePost" name="NamePost" required value="@Model.NamePost" style="margin:10px;" />
                </div>
            </div>
            <div class="form-group">@Html.Action("SelectCategory", "Categories")</div>
            <div class="form-group">
                <label for="Description" class="col-sm-2 control-label">Краткое описание</label>
                <div class="col-md-10">
                    <textarea rows="3" class="form-control" id="Description" name="Description" required placeholder="Введите краткое описание, максимум 200 символов" maxlength="200" style="margin:10px;">@Model.Description</textarea>
                </div>
            </div>

            <div class="form-group">
                <label for="contentPost" class="col-sm-2 control-label">Содержимое поста</label>
                <div class="col-md-10">
                    <textarea class="ckeditor form-control" name="contentPost" id="contentPost" rows="6" style="visibility: hidden; display: none;">@Model.contentPost</textarea>
                    <script type="text/javascript">

                    </script>
                </div>

                <hr />
                <div class="form-group">
                    <label for="Tags" class="col-sm-2 control-label">Тэги</label>
                    <div class="col-md-10">
                        <textarea cols="150" rows="3" class="form-control" id="Tags" name="Tags" required placeholder="Введите тэги через запятую" style="margin:10px;">@Model.Tags</textarea>
                    </div>
                </div>
                <div class="form-group ">
                    <label for="dateAddPost" class="col-sm-2 control-label">Дата создания</label>
                    <div class="col-md-10">
                        <input type="date" class="form-control" required name="dateAddPost" id="dateAddPost" style="margin:10px; width:400px;" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="File" class="col-sm-2 control-label">Прикрепить файл для Preview</label>
                    <div class="col-md-10">
                        <input type="file" class="form-control " name="Upload" id="Upload" style="margin:10px; width:400px; " />
                    </div>
                </div>

                <div align="right">
                    <br />
                    <input type="submit" class="btn btn-info " id="editPost" name="save" style="margin:10px;" />
                </div>

            </div>
        </div>
    </div>
</div>


@section scripts {
    <script>
        var files;
        $(document).ready(function () {
            $('#editPost').click(function () {
                for (instance in CKEDITOR.instances) {
                    CKEDITOR.instances[instance].updateElement();
                }
                files = document.getElementById('Upload').files;
                var data = new FormData();
                var item = document.getElementById("selectedCategory");
                var selected = $(':selected', item);
                var selectedCategory = selected.val();
                data.append("IdCategory", selectedCategory);
                data.append("NamePost", $("#NamePost").val());
                data.append("Description", $("#Description").val());
                data.append("contentPost", $("#contentPost").val());
                data.append("Tags", $("#Tags").val());
                data.append("dateAddPost", $("#dateAddPost").val());
                data.append("PostID", $("#id").val());
                data.append("Upload", files[0]);
                if (files[0] != null) {
                    data.append("upload", files[0].name);
                }
                for (instance in CKEDITOR.instances) {
                    CKEDITOR.instances[instance].updateElement();
                }
                $.ajax({
                    url: 'EditPost',
                    type: 'post',
                    contentType: false,
                    processData: false,
                    data: data,
                    success: function (data) {
                        document.location.href = "@Url.Action("Index","Posts")";
                        console.log(data);
                    }
                });
            });
        });

    </script>
}

Blog/Areas/Admin/Views/Posts/Index.cshtml
@model IEnumerable<IServices.Models.Post.ModelPost>

@{
    ViewBag.Title = "Posts";
}
<div id="PanelPosts"></div>




@section scripts{
  <script>
            $(document).ready(function () {
                $('#PanelPosts').load("@Url.Action("AjaxPosts", "Posts")");


            });


</script>
}

Blog/Areas/Admin/Views/Posts/NewPost.cshtml
@{
    ViewBag.Title = "NewPost";
}


<div class="col-md-12">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-cogs">&nbsp;</i>Добавить пост
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
                <a href="javascript:;" id="reloadUsers" class="reload" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">
            
            <div class="form-group">
                <label for="NamePost" class="col-sm-2 control-label">Название</label>
                <div class="col-md-10">
                    <input type="text" class="form-control" id="NamePost" name="NamePost" required placeholder="Заголовок" style="margin:10px;" />
                </div>
            </div>
            <div class="form-group">@Html.Action("SelectCategory", "Categories")</div>
            <div class="form-group">
                <label for="Description" class="col-sm-2 control-label">Краткое описание</label>
                <div class="col-md-10">
                    <textarea rows="3" class="form-control" id="Description" name="Description" required placeholder="Введите краткое описание, максимум 150 символов" maxlength="150" style="margin:10px;"></textarea>
                </div>
            </div>

            <div class="form-group">
                <label for="contentPost" class="col-sm-2 control-label">Содержимое поста</label>
                <div class="col-md-10">
                    <textarea class="ckeditor form-control" name="contentPost" id="contentPost" rows="6" style="visibility: hidden; display: none;"></textarea>
                    <script type="text/javascript">

                    </script>
                </div>

                <hr />
                <div class="form-group">
                    <label for="Tags" class="col-sm-2 control-label">Тэги</label>
                    <div class="col-md-10" >
                       <div style="margin:10px;">
                           <select multiple data-role="tagsinput" id="Tags" name="Tags">
                               
                           </select></div>
                        
                    </div>

                </div>
                <div class="form-group ">
                    <label for="dateAddPost" class="col-sm-2 control-label">Дата создания</label>
                    <div class="col-md-10" >
                        <input type="date" class="form-control" required name="dateAddPost" id="dateAddPost"style="margin:10px; width:400px;" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="File" class="col-sm-2 control-label" >Прикрепить файл для Preview</label>
                    <div class="col-md-10">
                        <input type="file" class="form-control " name="Upload" id="Upload" style="margin:10px; width:400px; " required/>
                    </div>
                </div>

                <div align="right" >
                    <br />
                    <input type="submit" class="btn btn-info " id="addNewPost" name="save"style="margin:10px;" />
                </div>
                <input type="hidden" id="User" value="@User.Id"/>
            </div>
        </div>
    </div>
</div>



@section scripts {
    <script>
        var files;
   
    $(function () {
        $("[data-autocomplete-source]").each(function () {
            var target = $(this);
            target.autocomplete({ source: target.attr("data-autocomplete-source") });
        });
    });

        $(document).ready(function () {

            $("#Tags").tagsinput('items');
         
            $('#addNewPost').click(function () {
                for (instance in CKEDITOR.instances) {
                    CKEDITOR.instances[instance].updateElement();
                }

                files = document.getElementById('Upload').files;
                var data = new FormData();
                var item = document.getElementById("selectedCategory");
                var selected = $(':selected', item);
                var selectedCategory = selected.val();
                data.append("IdCategory", selectedCategory);
                data.append("NamePost", $("#NamePost").val());
                data.append("Description", $("#Description").val());
                data.append("contentPost", $("#contentPost").val());
                data.append("Tags", $("#Tags").val());
                data.append("dateAddPost", $("#dateAddPost").val());
                data.append("Upload", files[0]);
                data.append("upload", files[0].name);
                data.append("User", $("#User").val());

                for (instance in CKEDITOR.instances) {
                    CKEDITOR.instances[instance].updateElement();
                }
                $.ajax({
                    url: 'NewPost',
                    type: 'post',
                    contentType: false,
                    processData: false,
                    data: data,
                    success: function (data) {
                        document.location.href = "@Url.Action("Index","Posts")";
                        console.log(data);
                    }
                });
            });

        });

    </script>
}

Blog/Areas/Admin/Views/Posts/Posts.cshtml
@model IEnumerable<IServices.Models.Post.ModelPost>

@{
    ViewBag.Title = "Posts";
}
<div id="PanelPosts"></div>




@section scripts{
  <script>
            $(document).ready(function () {
                $('#PanelPosts').load("http://localhost:62712/Admin/Posts/AjaxPosts");


            });


</script>
}